### ISSUE TITLE
Echec de compilation pour la branche master

### ISSUE THREAD

**Issue by ngrosshans** [GL-MPRI-2014/GL_MPRI_2014#156]
La branche `master` ne compile plus depuis maintenant deux jours, depuis le dernier commit (le dernier commit pour lequel la compilation fonctionnait est e1f73fa33b635666e61902a0f71953144326eac6).

Le message d'erreur indiqué par Travis est le suivant : 
```
File "src/common/config/Config.ml", line 25, characters 2-17:
Error: Unbound value ConfigLog.infof
Hint: Did you mean info?
Command exited with code 2.
Hint: Recursive traversal of subdirectories was not enabled for this build,
as the working directory does not look like an ocamlbuild project (no
'_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
you should add the option "-r" or create an empty '_tags' file.

To enable recursive traversal for some subdirectories only, you can use the
following '_tags' file:

true: -traverse
<dir1> or <dir2>: traverse
```
A priori un problème avec le système de logs, une fonction qui ne semble pas exister. Les lignes concernées par l'erreur ont été modifiées par @dbusatto le 3 décembre, par contre, je ne m'explique pas pourquoi l'erreur survient seulement maintenant.

**Comment by VLanvin** [comment]
Je ferme puisque visiblement plus personne n'a de problèmes.
