### ISSUE TITLE
IA et brouillard de guerre

### ISSUE THREAD

**Issue by teoule17** [GL-MPRI-2014/GL_MPRI_2014#164]
Désormais, la fonction src_armyof prend en compte le brouillard de guerre. Elle renvoie uniquement les unités visibles par votre player.
Quelques changements à prévoir pour les différentes IA.

**Comment by iSheeft** [comment]
Est-ce que ceci n'est pas réglé maintenant ?

**Comment by VLanvin** [comment]
Je pense que c'est bon oui, c'était plus une notification qu'un problème.
