### ISSUE TITLE
Game over & brouillard de guerre

### ISSUE THREAD

**Issue by VLanvin** [GL-MPRI-2014/GL_MPRI_2014#167]
Voici plusieurs problèmes tous adressés à @teoule17.

J'ai trouvé quelques problèmes dans la gestion du game over (et j'ai un peu de mal à les corriger) : 

- Quand on capture un des deux QG ennemis, ça lance un game over et la partie se bloque. Je ne crois pas que ça soit voulu.

- Quand on se fait capturer notre QG ou que toutes nos unités sont détruites, le jeu continue. De plus, dans le cas où on n'a plus d'unités, l'engine continue de nous demander de jouer (il faut donc passer son tour) !

Il y a aussi un problème avec le brouillard de guerre, je n'affiche que les unités visibles mais apparemment elles le sont toutes... C'est normal ?

**Comment by VLanvin** [comment]
Tout est réglé à part un problème, qui est traité dans #187 .

**Comment by iSheeft** [comment]
Il faudrait peut-être ouvrir un ticket concernant le brouillard de guerre.
Son comportement n'est toujours pas le bon.
Et d'ailleurs plusieurs fonctions (visible_unit, visible_army_for, …) ne sont pas cohérentes avec le brouillard affiché.
