### ISSUE TITLE
Sous-sablins

### ISSUE THREAD

**Issue by iSheeft** [GL-MPRI-2014/GL_MPRI_2014#169]
![capture d ecran 2014-12-18 a 20 11 44](https://cloud.githubusercontent.com/assets/5960860/5494201/31360066-86f2-11e4-92b0-fef08bf2497f.png)
Je comprends que ce soit compliqué à gérer puisque les ports sont sur la plage, mais est-ce qu'on veut vraiment pouvoir naviguer dans le sable ?

**Comment by VLanvin** [comment]
On peut toujours créer une tuile spéciale qui aurait le sprite du sable mais qui serait uniquement utilisée sous les ports et qui serait walkable/navigable non ? Ajouter une tuile au xml est simple, donc pourquoi s'en priver.

**Comment by iSheeft** [comment]
Ouais, c'est sans doute le mieux !

**Comment by dbusatto** [comment]
je suis d'accord, je vais m'en charger

**Comment by dbusatto** [comment]
ça devrait être bon
