### ISSUE TITLE
Bâtiments sur la minimap

### ISSUE THREAD

**Issue by iSheeft** [GL-MPRI-2014/GL_MPRI_2014#170]
Peut-être pourrions-nous rajouter les bâtiments sur la minimap ?

Je ne sais pas trop comment par contre, est-ce qu'on les représenter comme des unités ?

**Comment by VLanvin** [comment]
Voilà, les unités brillent et les bâtiments sont affichés en "mat". J'aurais plus qu'à commenter le module minimap :)
