### ISSUE TITLE
tests : position du curseur & map "vide"

### ISSUE THREAD

**Issue by dbusatto** [GL-MPRI-2014/GL_MPRI_2014#172]
Dans l'optique de faire des tests, il est ressorti jeudi qu'on aimerai bien contrôler la position initiale du curseur / avoir des maps simple pour tester une attaque, une mort d'unité, etc...

Du coup voilà comment faire : 
Pour le curseur, il y a pour l'instant deux possibilités, je peut en ajouter facilement n'hésitez pas a demander : 
- par défaut, le curseur d'un joueur démarre sur son bâtiment principal
- il est possible de l'initialiser sur une unité "ayant de la place à gauche", pour ça il suffit d'appeler
 Config.config#settings_engine.cursor_init <- `Unit avant de faire un "new Fieldgenerator.t players_list"

Pour avoir une map de taille x*y constituée uniquement de plaine, appeler :
open Settings_t et open Settings_engine_t en début de fichier, puis à l'endroit voulu :
config#settings.map_width <- x;
config#settings.map_height <- y;
 config#settings_engine.generation_method <- `Dummy;
let generator = new FieldGenerator.t players_list

A noter que la génération place sur cette map la quantité initiale d'unités paramétrée par la config d'unités, donc si la taille est trop petite, la génération va échouer pour cause de place insuffisante.

Je vais prochainement ajouter un moyen de faire simplement une map 2*2 avec deux unités, histoire de tester une mini partie dans des conditions réeles

**Comment by iSheeft** [comment]
Est-ce que c'est réglé @dbusatto ?

**Comment by dbusatto** [comment]
et bien... je suis un peu dans le caca sur le reste des trucs a faire ces vacances, j'ai pas trop touché au GL, mais je viens de tester et X/W me semblent bien, et suffisants pour d'éventuels tests faits (pas par moi) d'içi ce soir
