### ISSUE TITLE
Animations Asynchrones

### ISSUE THREAD

**Issue by iSheeft** [GL-MPRI-2014/GL_MPRI_2014#173]
Actuellement, les animations dans l'interface (pour les déplacements) sont asynchrones.
Ce qui peut donner lieu à des incohérences lors de l'affichage (une unité est tuée avant que son assaillant n'ai terminé son déplacement).

Il serait possible de tout séquentialiser en récupérant les mises à jour une à une (et en attendant la fin de l'animation en cours avant d'en récupérer une autre).
On pourrait alors plus naturellement envisager des animations pour les combats (enfin je pense qu'on n'aura pas le temps de faire grand chose).

La contrepartie est sans doute au niveau de la rapidité d'exécution…

Prenons-nous la peine de faire ce travail ?

**Comment by iSheeft** [comment]
Je continue mon monologue.
Ça se précise un peu. J'ai réussi à séparer (à priori) les players possédés par le moteur et par l'interface (à part pour le brouillard de guerre ?).
J'ai ajouté au module `Updates` la gestion de ces mises à jour (elles ne sont plus que graphiques).
Ça reste à terminer.

Par contre, quelques trucs sont cassés à cause de ça (notamment l'information sur la case, `data#player_of` lance `assert false` sur une unité qu'il m'a renvoyé. Je ne comprends pas bien comment c'est possible.

**Comment by iSheeft** [comment]
J'ai vraiment plein de problèmes avec ces modifications !
J'ai encore des bugs débiles que je ne comprends pas… A priori, maintenant on peut s'attaquer soi-même…

A part ça, le module est plutôt en phase terminale. Il faut débogguer pour trouver d'où viennent ces foutus problèmes.
Est-ce que ça tente quelqu'un de m'expliquer ce que je fais de travers ?
(Normalement, la fonction `ack_update` seule est à regarder).

**Comment by VLanvin** [comment]
Je pense (je n'ai pas regardé le fonctionnement en détail, c'est donc juste un premier coup d'oeil) que le problème vient des Oo.copy. Je pense que lorsqu'on récupère l'unité sous le curseur, on récupère l'originale, mais on tente de la comparer à sa copie dans l'armée du joueur, ce qui renverra faux (ou inversement). Elle sera donc déclarée non-alliée et pourra être attaquée. 

PS : Je sais que ça ne vient pas de toi, mais c'est quoi cette update "Classement" ?!?

**Comment by iSheeft** [comment]
Donc, les problèmes maintenant seraient localisés dans `Game`. C'est possible en effet.
(Il doit y avoir un problème par là puisqu'il est également impossible de construire des unités également).

Pour ce qui est de l'update Classement, c'est vraiment bizarre. Elle n'a pas d'argument donc je ne vois pas vraiment l'intérêt…

**Comment by iSheeft** [comment]
Une solution consisterait donc à passer aux comparaisons d'id pour tous ces objets (players, bâtiments, unités) plutôt que l'égalité classique.
Ou identifier l'endroit où il y a une inconsistance (plus propre et mieux sur le long terme, même si on peut le coupler avec la première solution) copie/pas copie.

J'ai testé pour la construction de bâtiments, si on utilise la comparaison d'id ça fonctionne…

**Comment by VLanvin** [comment]
J'ai fixé l'auto-attaque en comparant sur les id dans Logics (fonction units_in_range). Mais je n'arrive quand même pas à comprendre pourquoi le test d'égalité renvoyait faux, je ne vois pas où les joueurs auraient pu être copiés.

**Comment by iSheeft** [comment]
Parfois certaines unités d'un même joueur se gênent pour le déplacement. Elles ne peuvent plus s'attaquer, mais ça reste ennuyeux.

**Comment by VLanvin** [comment]
Il va falloir aller chercher tous les endroits où on a fait une comparaison simple et changer par un test sur les ids :)

**Comment by iSheeft** [comment]
Ce qui m'échappe, c'est pourquoi des successions comme celles-ci ne fonctionnent pas :
```ocaml
let old_b = Logics.building_of_id b#get_id data#players data#neutral_buildings in
let player = Logics.find_player pid data#players in
player#delete_building old_b#get_id
```

La troisième ligne me renvoie un `Not_found`, je trouve ça curieux.

**Comment by VLanvin** [comment]
Au passage, sur un sujet un peu différent, il faudrait quand même que j'implémente une meilleure gestion des threads (avec un mutex). Du coup, je me demandais, il y a moyen de savoir quand une animation est terminée ? Je pense que ça serait pas mal de bloquer/débloquer le mutex au début/fin de l'anim.

Pour ton message : déjà je trouve pas terrible que le Not_found ne soit pas catché par Player... Mais à part ça, si tu remplaces old_b#get_id par b#get_id dans la dernière ligne, ça ne marche pas non plus ?

**Comment by iSheeft** [comment]
Tu as la méthode `update` qui est celle appelée à l'extérieur, elle vérifie si il y a une animation en cours (qui peut être une pause d'un certain nombre de frames, ça peut se changer pour devenir un temps de sleep) et sinon, on lit d'éventuelles nouvelles updates.
Sinon, on peut transformer l'utilisation de la variable d'instance avec des accesseurs internes qui font quelque chose lors d'un Rien -> Autre ou Autre -> Rien.

Non, ça ne change rien. En même temps c'est normal puisque d'après la fonction de recherche,
```ocaml
b#get_id = old_b#get_id
```

**Comment by iSheeft** [comment]
Et bien normalement, la mise à jour n'est pas effectuée, donc old_b correspond à ce que j'ai en mémoire (b sera sa future version).
Je récupère l'id de son propriétaire (s'il en a un) et dans ce cas, je supprime b de sa liste.

Si je me fais capturer un bâtiment avec cette ligne commentée, j'ai une superposition de deux bâtiments.
Si je la décommente, j'ai cette erreur dès le tour du joueur adverse.
Est-ce qu'il y aurait un doublon, mais pas pour le `actual_player` ?

----------

Remplacer les adds me semble une bonne idée.

**Comment by iSheeft** [comment]
On dirait aussi qu'il y a une double perte des PV parfois…
L'unité perd des PV avant l'animation, puis juste après.
C'est assez gênant.

**Comment by iSheeft** [comment]
J'ai du rajouter la comparaison par ID aussi dans Game pour pouvoir attaquer sans se déplacer.
On en déduit que `cdata#unit_at_position cursor#position` et `cdata#player_unit_at_position cursor#position cdata#actual_player` sur une position qui nous appartient ne renvoient pas la même unité, mais deux copies de la même.

**Comment by iSheeft** [comment]
J'ai fait une copie plus propre qui s'hérite sans problème.
J'ai aussi fait en sorte que le client_data possède deux players identiques pour actual_player et son équivalent dans la liste de tous les joueurs.

Enfin, je conserve uniquement une copie de cet actual_player (avant il était encore partagé avec le moteur je crois). Malheureusement, de ce fait, `cdata#actual_player#event_state` n'est pas mis à jour et il n'est plus possible de déplacer les unités… (J'en ai marre des ces bugs à la chaîne).

**Comment by iSheeft** [comment]
Je rajoute quelques mises à jours depuis le moteur parce que sinon certaines opérations ne sont plus faîtes que sur le moteur.
Je vous annonce donc le retour du marquage des unités jouées ainsi que celui de l'argent gagné.

En revanche, je me suis fait jeter par le moteur en voulant construire un hélicopter alors que j'avais 100 fleurs. Il reste donc du boulot pour la synchronisation.

**Comment by iSheeft** [comment]
J'ai corrigé l'affichage des unités adverses qui étaient initialement sous le brouillard de guerre.
Il semblerait que la méthode `data#visible_unit_at_position` ne donne pas le bon résultat…
(Le brouillard a toujours un comportement chaotique donc je ne sais pas trop d'où ça vient).

**Comment by iSheeft** [comment]
J'ai l'impression qu'on commence à en voir le bout. Avec un peu de chance ça pourra aller dans master d'ici la deadline.

Petit récapitulatif :

* Les PV sont mieux gérés (en fait j'avais mal compris ce que représentait un paramètre, j'ai du aller lire le code);

* On peut de nouveau créer des unités sans que le moteur nous fasse passer le tour, l'argent est mis à jour et dépensé correctement;

* J'ai touché à beaucoup de fichiers pour changer le type `Action.t` de sorte qu'il n'utilise plus que des identifiants;

* Le moteur envoie aussi la mise à jour concernant l'attaque si une unité est tuée;

* Enfin, j'ai décidé que le moteur gèrerait la destruction et l'ajout des bâtiments lui-même (après tout, il y avait des mise à jours prévues à cet effet mais elles n'étaient pas utilisées) et ça a pour effet de corriger (enfin !) le bug associé aux bâtiments.

Il va falloir faire de nouveau un tour du propriétaire pour vérifier que tout fonctionne correctement (aux bogues de master près bien entendu).

J'apprécierai des retours (surtout que là je suis content donc il faut me briser le moral :)).

**Comment by PLBegay** [comment]
Catégories réécriture catégories réécriture catégories réécriture
catégories réécriture catégories réécriture catégories réécriture
catégories réécriture catégories réécriture.

De rien.
Le 3 janv. 2015 18:29, "Théo Winterhalter" <notifications@github.com> a
écrit :

**Comment by VLanvin** [comment]
Pas bien de spammer les tickets, surtout que la deadline du GL est plus proche que celle de catégories, et encore plus que celle de réécriture :)

@iSheeft, j'ai fait une partie rapide en cherchant les bugs, j'en ai pas trouvé. Donc pour l'instant tout va bien !

**Comment by iSheeft** [comment]
Yay !
Je ferme le ticket (au moins temporairement) et je balance une pull request.
