### ISSUE TITLE
Plus de bâtiments au départ

### ISSUE THREAD

**Issue by iSheeft** [GL-MPRI-2014/GL_MPRI_2014#175]
Est-ce qu'on ne pourrait pas revoir la génération pour donner une ou deux usines à chaque armée au début plutôt qu'une bonne base d'unités ?
Souvent dans ce genre de jeu, à part en mode histoire (mais ça parait un peu tard), on démarre sans unité sur le terrain.

**Comment by iSheeft** [comment]
Et encore une fois, je pense que si on laisse un seul aéroport, il n'y aura jamais de batailles aériennes (tu peux bien sûr me rétorquer que je n'ai jamais fait d'autres avions que l'hélico).

**Comment by VLanvin** [comment]
Je suis plutôt d'accord avec le fait de n'avoir que des bâtiments au début. Mais avant ça, il faudrait régler le fait que le jeu termine lorsque l'adversaire n'a plus d'unités.
Et pareil, avoir au moins un aéroport par personne (à aller capturer) serait peut-être mieux.

**Comment by iSheeft** [comment]
C'est maintenant réglé, on peut donc partir sans unité maintenant !
Je suis aussi d'accord pour l'aéroport (c'est un peu inutile si un seul joueur peut en avoir un).

**Comment by VLanvin** [comment]
Ca a été réglé, je ferme donc le ticket.
