### ISSUE TITLE
Crédits (personne)

### ISSUE THREAD

**Issue by Saroupille** [GL-MPRI-2014/GL_MPRI_2014#177]
Je viens de voir un mail avec le titre Crédit et du coup, je crée ce ticket pour évoquer l'idée d'ajouter un menu crédit au jeu. On pourrait s'amuser à faire un truc rigolo, au lieu de mettre juste les noms des gens ayant contribués au projet.

**Comment by iSheeft** [comment]
Si on veut faire ça, il faut se décider à associer à chacun un qualificatif.
C'est sans doute plus compliqué que de le coder.

Le chargement est devenu trop rapide pour le faire dessus par contre non ?

**Comment by VLanvin** [comment]
Pour les crédits je verrais bien un bouton sur le menu principal. Ca me parraît plus pratique et moins encombrant que pendant un chargement.

Sinon, c'est pas forcément la peine d'avoir un qualificatif par personne, on peut plutôt regrouper tout le monde en catégories (bidons), avec un nom pouvant apparaître dans plus d'une catégorie éventuellement.

**Comment by iSheeft** [comment]
Oui d'accord. Les catégories sont basées sur des trucs sérieux ? Genre interface, moteur, script, réseau, etc. ?

**Comment by VLanvin** [comment]
Perso je serais plutôt pour un truc pas sérieux, mais il faudrait l'avis de plus de monde.

**Comment by iSheeft** [comment]
Je suis d'accord, mais je voulais dire qu'on mettait quand même ensemble les gens ayant travaillé ensemble.

**Comment by VLanvin** [comment]
Oui on peut faire ça. Il faut trouver des bonnes idées de catégories (à défaut d'en avoir pour la présentation de j-espère-pas-demain).

Les premières qui me viennent à l'esprit (à la louche) : Textures Hardcoding, Fireworks, Minimap Mipmapping, Konami Snake, Clickodromization, Bugs Implementation, Flower Cultures, Debugger Debugging, Model Checking & Code Verification (catégorie éventuellement vide), "Yeah !" Recording, Scriptable Script Generator Scripting...  

Je vais m'arrêter là je crois !

**Comment by iSheeft** [comment]
Ça me semble plutôt pas mal en effet !
Un bouton **Credits** sur le menu principal donc ?

**Comment by iSheeft** [comment]
Je sais pas trop sous quelle forme on le veut en fait.
On veut du texte qui défile ? Qui change (avec un timer ? avec la barre d'espace ?) ?

**Comment by VLanvin** [comment]
Un texte qui défile de bas en haut ~avec des feux d'artifice~ !

**Comment by PLBegay** [comment]
Et des rivières bordel !

**Comment by iSheeft** [comment]
Bon voilà, le système de crédits est opérationnel.
J'ai pas vraiment rempli parce que je ne sais pas trop qui veut être affiché où.
N'hésitez pas à faire un tour dans `Credits.ml` !

**Comment by VLanvin** [comment]
J'ai un peu amélioré les crédits dans la branche `amaze`. J'ai entre autres ajouté tous ceux qui n'y étaient pas, ainsi que deux trois autres petites choses... Je ne vais pas tarder à merger.

**Comment by iSheeft** [comment]
Il ne manque plus que de la musique, j'imagine que si @Artymort et @tbazin ont le temps, ils le feront.
On peut donc sans doute fermer sans scrupules.
Merci !
