### ISSUE TITLE
Capture base énnemie

### ISSUE THREAD

**Issue by dbusatto** [GL-MPRI-2014/GL_MPRI_2014#179]
a chaque fois que je capture la base d'un de mes deux ennemis, je fait un Not_found
Si ce ticket fait doublet avec un autre, fermez le

**Comment by iSheeft** [comment]
Tu as la backtrace ? (Si besoin est, j'ai mis dans le README comment faire).
Ce serait intéressant de savoir d'où ça vient.

**Comment by VLanvin** [comment]
Idem lorsqu'un ennemi capture un de mes bâtiments, ça me sort un Not_found. Je vais essayer d'avoir la backtrace.

**Comment by iSheeft** [comment]
Normalement, c'est le bug #187 qui a été corrigé.

**Comment by VLanvin** [comment]
Effectivement désolé, ma branche était en retard.

**Comment by dbusatto** [comment]
je suis a jour, mais a chaque fois que je capture l'une des bases énnemies, je récupère le backtrace : 
Thread 5 killed on uncaught exception Not_found
Raised at file "hashtbl.ml", line 136, characters 19-28
Called from file "src/common/Player.ml", line 75, characters 14-41
Called from file "src/engine/Game_engine.ml", line 43, characters 8-30
Called from file "list.ml", line 73, characters 12-15
Called from file "array.ml", line 73, characters 31-48
Called from file "src/engine/Game_engine.ml", line 270, characters 26-46
Called from file "src/engine/Game_engine.ml", line 276, characters 4-23
Called from file "src/engine/Game_engine.ml", line 166, characters 25-38
Called from file "thread.ml", line 37, characters 8-14

Et le jeu s'arrète (j'ai toujours le controle de mon curseur)

**Comment by iSheeft** [comment]
Oui, je parlais du bug mentionné par @VLanvin.
Je n'ai pas corrigé celui-ci malheureusement.

**Comment by iSheeft** [comment]
Bon, alors c'était un peu bizarre.
Lors de la capture d'une base (c'est vraiment trop facile !), le joueur concerné est déclaré mort : toutes ses unités sont supprimées, et ce autant de fois qu'il y a de joueur (autant dire que dès le deuxième il y a un problème).
C'est donc réglé !
