### ISSUE TITLE
Comment la vie est unités descend ?

### ISSUE THREAD

**Issue by Saroupille** [GL-MPRI-2014/GL_MPRI_2014#185]
Je ne sais pas à qui je m'adresse mais @juliengrange a ajouté il y a un certains temps une méthode dans le fichier src/comon/Player.ml une méthode : set_unit_hp . Le but de cette méthode est de mettre à jour les hp d'une unité blessée. Cependant, cette méthode n'a jamais été implémentée et est pourtant utilisée dans src/engine/Game_engine à la ligne 138. Cette méthode est appelée lors d'une update de type Set_unit_hp .

Donc comment la vie des unité descend actuellement ? A quoi sert cette méthode par conséquent ?

**Comment by iSheeft** [comment]
Il y a effectivement un doublon et un duel de philosophies j'imagine.
La classe `Unit.t` implémente les méthodes nécessaires pour se déplacer, perdre de la vie, … Bref toutes les opérations de la vie courante.
Le player a la liberté d'effectuer des opérations supplémentaires pour ce genre d'opérations.
Pour le déplacement, la méthode est bel et bien appelée, mais ce n'est pas le cas (enfin elle est appelée mais vide) pour `set_unit_hp`. Au moment de la mise à jour, le moteur (entendre ici `Game_engine`) fait directement appel aux méthodes de l'unité.

**Comment by Saroupille** [comment]
Tu peux m'indiquer où ça se fait dans le Game engine ? Car la seule chose que je vois c'est la ligne 138 dans le fichier game_engine.  

`Array.iter (fun x -> x#update (Types.Set_unit_hp(u2#get_id,u2#hp,(player_u2#get_id))) ) players`

**Comment by iSheeft** [comment]
https://github.com/GL-MPRI-2014/GL_MPRI_2014/blob/master/src/engine/Game_engine.ml#L163
