### ISSUE TITLE
Pas de Your_turn au premier tour

### ISSUE THREAD

**Issue by iSheeft** [GL-MPRI-2014/GL_MPRI_2014#189]
Actuellement, le moteur n'envoie d'information concernant les tours qu'à partir du premier changement.
Le joueur qui ouvre le jeu n'a donc pas le droit à son `Your_turn` au début de partie.

Ce serait possible ?
D'ailleurs, j'ai rajouté `Turn_of player_id` qui est envoyé aux autre joueurs pour savoir qui joue actuellement, j'aimerais bien que ce soit donc envoyé de la même façon pour le tout premier tour.

Merci !

**Comment by VLanvin** [comment]
J'ai passé les signaux au début du code plutôt qu'à la fin, donc normalement ils sont bien transmis au début du tour.
