### ISSUE TITLE
Langage de script : information sur un Soldier

### ISSUE THREAD

**Issue by OlivierMarty** [GL-MPRI-2014/GL_MPRI_2014#190]
Il n'y a pas de fonctions comme get_life : soldier-> int. En tant que joueur humain, on les voit dans l'interface, est-ce qu'on veut y avoir accès pour une IA ?

**Comment by VLanvin** [comment]
Oui, idéalement (et j'insiste sur le idéalement), il faudrait que l'IA ait accès à tout ce dont un joueur humain aurait accès, ou pourrait déduire (par exemple les couts de déplacement). J'ai ajouté la fonction `life_of`, je l'ajoute au wiki.

Au passage, si tu veux que j'ajoute certaines fonctions, tu peux le dire dans #168 , il est fait pour ça :)

**Comment by OlivierMarty** [comment]
Merci !
