### ISSUE TITLE
Condition de victoire et capture

### ISSUE THREAD

**Issue by iSheeft** [GL-MPRI-2014/GL_MPRI_2014#195]
Pour l'instant, la capture d'une base se fait en un seul tour, et il suffit donc de se trouver sur la base d'un ennemi pour le tuer sans lui laisser le temps de réagir.
C'est un peu dommage de pouvoir mourrir aussi facilement.

**Comment by VLanvin** [comment]
D'ailleurs, si on tue toutes les unités ennemies, le jeu se bloque. On ne peut plus rien faire, mais on n'a pas de son de victoire ni rien. C'est étrange, surtout qu'on aimerait que le jeu continue tant que l'ennemi a son QG (enfin je pense).

**Comment by iSheeft** [comment]
Sur une suggestion de @MetaMetaMath, les bâtiments sont capturés au début de son propre tour.
Cela devrait ainsi permettre de rendre les choses un peu plus difficiles concernant la capture de la base ennemie (après je sais pas si les IA sont alertées par ce genre d'attaque).

**Comment by iSheeft** [comment]
On ne perd plus quand son armée est décimée maintenant.
Il va falloir que les IA prennent en compte cette façon de gagner maintenant.
