### ISSUE TITLE
batiments ennemis après game over

### ISSUE THREAD

**Issue by dbusatto** [GL-MPRI-2014/GL_MPRI_2014#197]
lorsque la base d'un ennemi est capturée, toutes ses unitées disparaissent, mais seule une partie de ses batiments redeviens neutre, je ne pense pas que ce soit voulu.

Les batiments qui ne redeviennent pas neutres sont ceux qui étaient neutres au départ (donc tous sauf la ville et la factory de départ),

**Comment by iSheeft** [comment]
A priori c'est réglé !
