### ISSUE TITLE
Script: assoc_set/get incorrectly registered

### ISSUE THREAD

**Issue by dbaelde** [GL-MPRI-2014/GL_MPRI_2014#210]
In `ScriptCore.ml`, fst/snd are used to register set/get, which is not the right behaviour but also not the right type:
```
  expose scr_fst (`Fun_t(assoc_t a0 a1, setter_t)) "assoc_set";
  expose scr_snd (`Fun_t(assoc_t a0 a1, getter_t)) "assoc_get";
```
EDIT: Ceci est un mémo, et certainement pas un bug à traiter avant demain matin!

**Comment by OlivierMarty** [comment]
En fait, sauf erreur de ma part, ce n'est pas un bug.
Les `map` sont des paires de deux fonctions, et donc `assoc_get` et `assoc_set` sont simplement les projections.

De plus, les `map` sont testées dans le test check_script, ce qui me donne un degrés de confiance en plus ;)

**Comment by OlivierMarty** [comment]
Les deux fonctions partagent la même référence, ce qui permet de coder les map dans un langage dont le système type ne le permet pas directement.

**Comment by dbaelde** [comment]
OK, merci pour l'explication!

2015-01-14 17:11 GMT+01:00 Olivier Marty <notifications@github.com>:

> Les deux fonctions partagent la même référence, ce qui permet de coder les
> map dans un langage dont le système type ne le permet pas directement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GL-MPRI-2014/GL_MPRI_2014/issues/210#issuecomment-69940627>
> .
>



-- 
David
